### 

GET http://localhost:8000 HTTP/1.1

###

GET http://localhost:8000/usersMySql HTTP/1.1

###

GET http://localhost:8000/contact/elie HTTP/1.1

###

GET http://localhost:8000/articles HTTP/1.1

###

GET http://localhost:8000/articles/2 HTTP/1.1

###

DELETE http://localhost:8000/users/2 HTTP/1.1

###